baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Spencer Karau'
theme = 'PaperMod'


[params.homeInfoParams]
Title = "Hello!"
Content = "Welcome to my site! Here you will find some posts about my research as well as some personal information about me."

[[params.socialIcons]]
Title = 'LinkedIn'
name = "LinkedIn"
url = "https://www.linkedin.com/in/spencerkarau/"

[[params.socialIcons]]
Title = 'GitHub'
name = "GitHub"
url = "https://github.com/SpencerKarau"

[[menu.main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 20


[[menu.main]]
identifier = "labsite"
name = "Lab Website"
url = "https://kharoubalab.weebly.com/"
weight = 30



